export {
  fromLspCharacter,
  fromLspPosition,
  type HumanPosition,
  type LspPositionParts,
  type PositionEncoding,
  PREFERRED_ENCODINGS,
  resolvePositionEncoding,
  toLspCharacter,
  toLspPosition,
} from './encoding.js'
export {
  type DocumentSymbol,
  decideStatus,
  type Hover,
  type Location,
  type LocationLink,
  type LspPosition,
  type LspRange,
  type MarkedString,
  type MarkupContent,
  type NormalizedHover,
  type NormalizedLocation,
  type NormalizedSymbol,
  normalizeDocumentSymbols,
  normalizeHover,
  normalizeLocations,
  type QueryStatus,
  type SymbolInformation,
  symbolKindName,
} from './normalize.js'
